<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>Lemo</string>
	<key>fileTypes</key>
	<array>
		<string>lemo</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\blemo</string>
	<key>foldingStartMarker</key>
	<string>^\s*class\s+\S.*$|.*(-&gt;|&lt;&gt;)\s*$|.*[\[{]\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*[}\]]\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>name</key>
	<string>Lemo</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.lemo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"""</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.lemo</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.heredoc.lemo</string>
			<key>patterns</key>
			<array>
				<dict>
                    <key>match</key>
                    <string>\\(x..|u....|[^xu(])</string>
                    <key>name</key>
                    <string>constant.character.escape.lemo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_lemo</string>
				</dict>
			</array>
		</dict>
        <dict>
            <key>begin</key>
            <string>"</string>
            <key>beginCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.begin.lemo</string>
                </dict>
            </dict>
            <key>end</key>
            <string>"</string>
            <key>endCaptures</key>
            <dict>
                <key>0</key>
                <dict>
                    <key>name</key>
                    <string>punctuation.definition.string.end.lemo</string>
                </dict>
            </dict>
            <key>name</key>
            <string>string.quoted.double.lemo</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x..|u....|[^xu(])</string>
                    <key>name</key>
                    <string>constant.character.escape.lemo</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#interpolated_lemo</string>
                </dict>
            </array>
        </dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
			<key>name</key>
			<string>meta.normal.lemo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!#)###(?!#)</string>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lemo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>###(?:[ \t]*\n)</string>
			<key>name</key>
			<string>comment.block.lemo</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#)(?!\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.comment.lemo</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>comment.line.number-sign.lemo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)
				\b(?&lt;![\.\$])(
                    and|as|catch|class|cls|delete|do|else|false|finally|fun|get|
                    if|in|is|isnt|match|me|Me|mod|new|nonew|not|null|or|rem|return|self|set|
                    static|super|then|throw|true|try|void
				)(?!\s*:)\b
			</string>
			<key>name</key>
			<string>keyword.control.lemo</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?x)
				\*|\/|\-|\+|=|&lt;|&gt;|
				\?|\||\:|
                '[\w]*
			</string>
			<key>name</key>
			<string>keyword.operator.lemo</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolated_lemo</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\\\(</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.lemo</string>
						</dict>
					</dict>
					<key>end</key>
					<string>\)</string>
					<key>name</key>
					<string>source.lemo.embedded.source</string>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.lemo</string>
	<key>uuid</key>
	<string>A9F44CBB-014C-42C2-A275-4E53162D69D4</string>
</dict>
</plist>
