<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>name</key>
    <string>Lemo</string>
    <key>scopeName</key>
    <string>source.lemo</string>
    <key>uuid</key>
    <string>A9F44CBB-014C-42C2-A275-4E53162D69D4</string>
	<key>comment</key>
	<string>Lemo</string>
	<key>fileTypes</key>
	<array>
		<string>lemo</string>
	</array>
	<key>firstLineMatch</key>
	<string>^#!.*\blemo</string>
	<key>foldingStartMarker</key>
	<string>^\s*class\s+\S.*$|.*(-&gt;|&lt;&gt;)\s*$|.*[\[{]\s*$</string>
	<key>foldingStopMarker</key>
	<string>^\s*$|^\s*[}\]]\s*$</string>
	<key>keyEquivalent</key>
	<string>^~L</string>
	<key>patterns</key>
	<array>
		<dict>
            <key>contentName</key>
            <string>string.quoted.double.lemo</string>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>patterns</key>
			<array>
				<dict>
                    <key>match</key>
                    <string>\\(x..|u....|[^xu(])</string>
                    <key>name</key>
                    <string>constant.character.escape.lemo</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#interpolated_lemo</string>
				</dict>
			</array>
		</dict>
        <dict>
            <key>contentName</key>
            <string>string.quoted.double.lemo</string>
            <key>begin</key>
            <string>"</string>
            <key>end</key>
            <string>"</string>
            <key>patterns</key>
            <array>
                <dict>
                    <key>match</key>
                    <string>\\(x..|u....|[^xu(])</string>
                    <key>name</key>
                    <string>constant.character.escape.lemo</string>
                </dict>
                <dict>
                    <key>include</key>
                    <string>#interpolated_lemo</string>
                </dict>
            </array>
        </dict>
		<dict>
            <key>name</key>
            <string>meta.normal.lemo</string>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>`</string>
		</dict>
		<dict>
            <key>name</key>
            <string>comment.block.lemo</string>
			<key>begin</key>
			<string>(?&lt;!#)###(?!#)</string>
            <key>end</key>
            <string>###(?:[ \t]*\n)</string>
		</dict>
		<dict>
            <key>name</key>
            <string>comment.line.number-sign.lemo</string>
			<key>begin</key>
			<string>#</string>
            <key>end</key>
            <string>\n</string>
		</dict>
		<dict>
            <key>name</key>
            <string>keyword.control.lemo</string>
			<key>match</key>
			<string>(?x)
				\b(?&lt;![\.\$])(
                    above|and|as|catch|delete|do|else|export|false|finally|fun|
                    if|import|in|is|isnt|match|me|Me|mod|new|nonew|not|null|or|rem|return|self|
                    static|super|then|throw|true|try|void
				)(?!\s*:)\b
			</string>
		</dict>
		<dict>
            <key>name</key>
            <string>keyword.operator.lemo</string>
			<key>match</key>
			<string>(?x)
                \+ | -(?!&gt;) | \* | / | \*\* | = | /= | &lt;(?!&gt;) | (?&lt;!&lt;)&gt; |
                &lt;= | &gt;= | \|&gt; | \? | :: | \| |
                '[\w]*
			</string>
		</dict>
        <dict>
            <key>name</key>
            <string>storage.type.function.lemo</string>
            <key>match</key>
            <string>-&gt;|&lt;&gt;</string>
        </dict>
        <dict>
            <key>name</key>
            <string>storage.type.class.lemo</string>
            <key>match</key>
            <string>\b(?&lt;![\.\$])class(?!\s*:)\b</string>
        </dict>
	</array>
	<key>repository</key>
	<dict>
		<key>interpolated_lemo</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
                    <key>name</key>
                    <string>source.lemo.embedded.source</string>
					<key>begin</key>
					<string>\\\(</string>
                    <key>end</key>
                    <string>\)</string>
					<key>captures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.section.embedded.lemo</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>$self</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</dict>
</dict>
</plist>
